blackyblack/symplyphysics

symplyphysics/definitions/acceleration_is_velocity_derivative.py
symplyphysics/definitions/current_is_charge_derivative.py
symplyphysics/laws/electricity/electric_charge_is_constant_in_isolated_system.py
test/definitions/current_is_charge_derivative_test
test/definitions/current_is_charge_derivative_test.py
test/electricity/electric_charge_is_constant_in_isolated_system_test.py

Current defined an derivative of Charge transferred. Charge conservation discribed.

New electrical def

---

symplyphysics/laws/waves/refraction_factor_from_media.py
test/waves/refraction_factor_from_media_test.py

Refraction factor

---

symplyphysics/laws/waves/speed_of_light_from_fundamentals.py

please suggest the better way to present this

speed_of_light

---

symplyphysics/laws/electricity/resistance_is_proportional_to_length.py
test/electricity/resistance_is_proportional_to_length_test.py

Quantity decorator doesnt work for me:
File "C:\Users\IRU\AppData\Local\Programs\Python\Python39\lib\site-packages\symplyphysics-0.0.1-py3.9.egg\symplyphysics\core\quantity_decorator.py", line 88, in <module>
TypeError: unsupported operand type(s) for |: 'ManagedProperties' and 'type'

Resistance initial commit

---

.gitignore
symplyphysics/laws/waves/wavespeed_from_medium_permittivity_permeability.py
test/waves/wavespeed_from_medium_permittivity_permeability_test.py

- add law "wavespeed_from_medium_permittivity_permeability"
- add test "wavespeed_from_medium_permittivity_permeability_test"
- add changes in .gitignore (venv)

Commit_#1. Add laws wavespeed_from_medium_p.

---

symplyphysics/laws/relativistic/relativistic_mass.py
test/relativistic/relativistic_mass_test.py

Added law for relativistic mass

relativistic mass first commit

---

symplyphysics/laws/thermodynamics/efficiency_factor.py
test/thermodynamics/efficiency_factor_test.py

The efficiency of a heat engine is the ratio of the useful energy used to the total amount of energy received by the system: $\eta = (Q_h - Q_r) / Q_h$.
Where: $Q_h$ -- the amount of heat transferred by the heater to the heat engine,  $Q_r$ -- the amount of heat transferred by the heat engine to the refrigerator, $\eta$ -- efficiency of the heat engine.

Creating an implementation of the heat engine efficiency equation

---

symplyphysics/laws/thermodynamics/laplas_pressure.py
test/thermodynamics/laplas_pressure_test.py

Under the curved surface of the liquid, in addition to the internal pressure, additional pressure is created due to the curvature of the surface. The excess pressure under the curved surface of the liquid is determined by the Laplace formula: $P_l = 2 * \sigma / R$
Where $P_l$ - Laplas pressure, $\sigma$ - surface tension of the liquid, $R$ - radius of surface curvature.

Create law for Laplas pressure

---

examples/dynamics/body_landing_speed.py

A soccer ball falls without initial velocity from a height. Find its speed before hitting the ground.
From the law of conservation of energy, potential energy passes into kinetic energy
$E_k = E_p$
$mv^2/2 = mgh$
Then
$v = \sqrt{2gh}$

Create example for landing speed from height

---

examples/dynamics/body_landing_speed.py

* [CREATE] Create example for landing speed from height
* [UPDATE] Update code for example solution
* [FIX] Fix type of argument in function

Create example for landing speed from height (#159)

---

symplyphysics/laws/condensed_matter/thermionic_emission_current.py
test/condensed_matter/thermionic_emission_current_test.py

Commit #1. Laws:thermionic emission.

---

symplyphysics/laws/relativistic/relativistic_length.py
symplyphysics/laws/relativistic/relativistic_mass.py
test/relativistic/relativistic_length_test.py
test/relativistic/relativistic_mass_test.py

relativistic length

---

symplyphysics/laws/condensed_matter/current_density_from_concentration_and_velocity_of_charge_carriers.py
test/condensed_matter/current_density_from_concentration_and_velocity_of_charge_carriers_test.py

Current density from the concentration and velocity of charge carriers

---

symplyphysics/laws/condensed_matter/current_density_from_mobility.py
test/condensed_matter/current_density_from_mobility_test.py

Commit #1. Current density from mobility.

---

symplyphysics/laws/condensed_matter/drift_velocity_of_charge_carriers.py
test/condensed_matter/drift_velocity_of_charge_carriers_test.py

Commit #1. Laws: drift velocity.

---

symplyphysics/laws/waves/frequency_of_the_electron_transition_in_hydrogen.py
test/waves/frequency_of_the_electron_transition_in_hydrogen_test.py

Commit #1. frequency_of_the_electron_transition_in_hydrogen

---

symplyphysics/laws/optics/refraction_angle_from_environments.py

I'm not sure about the correctness of the format of derivation...

Derivation Snell's law from Fermat's principle

---

symplyphysics/laws/nuclear/law_of_half_life.py
test/nuclear/law_of_half_life_test.py

Commit #1. the_law_of_half-life

---

symplyphysics/laws/electricity/electric_dipole_moment.py
test/electricity/electric_dipole_moment_test.py

Commit #1. electric_dipole_moment

---

symplyphysics/core/fields/operators.py
symplyphysics/laws/dynamics/fields/conservative_force_is_gradient_of_potential_energy.py
test/core/fields/operators_test.py
test/dynamics/fields/conservative_force_is_gradient_of_potential_energy_test.py

Unsure if there is a better way of writing the law and calculation, since I haven't found an analogue of `QuantityVector` for fields, but I tried my best.

Law potential force is gradient

---

symplyphysics/laws/electricity/energy_two_charges_from_distance_and_relative_permittivity.py
test/electricity/energy_two_charges_from_distance_and_relative_permittivity_test.py

Commit #1. energy_of_a_system_of_two_point_charges

---

symplyphysics/laws/electricity/capacity_of_spherical_capacitor.py
test/electricity/capacity_of_spherical_capacitor_test.py

Commit #1. capacity_of_spherical_capacitor

---

symplyphysics/laws/electricity/work_of_charge_transfer_from_charge_and_voltage.py
test/electricity/work_of_charge_transfer_from_charge_and_voltage_test.py

Commit #1. work_of_charge_transfer

---

symplyphysics/laws/electricity/potential_of_field_of_point_charge.py
test/electricity/potential_of_field_of_point_charge_test.py

Commit #1. potential_of_electrostatic_field_around_point_charge

---

symplyphysics/laws/electricity/electric_field_outside_charged_sphere.py
test/electricity/electric_field_outside_charged_sphere_test.py

Commit #1. electric_field_outside_charged_sphere

---

symplyphysics/laws/electricity/electric_field_of_infinite_charged_plane.py
test/electricity/electric_field_of_infinite_charged_plane_test.py

Commit #1. electric_field_of_infinite_charged_plane

---

symplyphysics/laws/electricity/voltage_from_current_and_resistance.py
test/electricity/voltage_from_current_and_resistance_test.py

Commit #1. voltage_from_current_and_resistance

---

symplyphysics/laws/electricity/potential_of_electrostatic_field.py
test/electricity/potential_of_electrostatic_field_test.py

Commit #1. potential_of_electrostatic_field

---

symplyphysics/laws/condensed_matter/resistance_from_temperature.py
test/condensed_matter/resistance_from_temperature_test.py

Commit #1. temperature_resistance

---

symplyphysics/laws/electricity/magnetic_field_intensity_of_infinite_wire.py
test/electricity/magnetic_field_intensity_of_infinite_wire_test.py

Commit #1. magnetic_field_intensity_of_infinite_wire

---

symplyphysics/laws/electricity/force_between_parallel_wires.py
test/electricity/force_between_parallel_wires_test.py

Commit #1. force_between_parallel_wires

---

symplyphysics/laws/electricity/maximum_moment_of_magnetic_field.py
test/electricity/maximum_moment_of_magnetic_field_test.py

Commit #1. maximum_moment_of_magnetic_field

---

symplyphysics/laws/electricity/magnetic_induction_of_wire.py
test/electricity/magnetic_induction_of_wire_test.py

Commit #1. magnetic_induction_of_wire

---

symplyphysics/laws/relativistic/relativistic_sum_of_velocities.py
test/relativistic/relativistic_sum_of_velocities_test.py

relativistic sum of velocities

---

symplyphysics/laws/electricity/ampere_law.py
test/electricity/ampere_law_test.py

Commit #1. ampere_law

---

symplyphysics/laws/electricity/magnetic_flux_from_induction_and_area.py
test/electricity/magnetic_flux_from_induction_and_area_test.py

Commit #1. magnetic_flux_from_induction_and_area

---

symplyphysics/laws/electricity/magnetic_induction_of_linear_conductor_of_finite_length.py
test/electricity/magnetic_induction_of_linear_conductor_of_finite_length_test.py

Commit #1. magnetic_induction_of_linear_conductor_of_finite_length

---

symplyphysics/laws/kinematic/rotational_inertia_cartesian_integral.py
test/kinematic/rotational_inertia_cartesian_integral_test.py

I attempted to find a form of the integral that includes the integration limits

Create law and test for rotational inertia integral

---

symplyphysics/laws/electricity/period_of_a_charged_particle_in_a_magnetic_field.py
test/electricity/period_of_a_charged_particle_in_a_magnetic_field_test.py

Commit #1. period_of_a_charged_particle_in_a_magnetic_field

---

symplyphysics/laws/electricity/energy_of_magnetic_field_of_solenoid.py
test/electricity/energy_of_magnetic_field_of_solenoid_test.py

Commit #1. energy_of_magnetic_field_of_solenoid

---

symplyphysics/laws/electricity/mass_of_the_substance_deposited_on_electrode.py
test/electricity/mass_of_the_substance_deposited_on_electrode_test.py

Commit #1. mass_of_the_substance_deposited_on_electrode

---

symplyphysics/laws/electricity/electrochemical_equivalent_from_molar_mass_and_valence.py
test/electricity/electrochemical_equivalent_from_molar_mass_and_valence_test.py

Commit #1. electrochemical_equivalent_from_molar_mass_and_valence

---

symplyphysics/laws/relativistic/relativistic_time_dilation.py
test/relativistic/relativistic_time_dilation_test.py

relativistic time dilation

---

symplyphysics/core/symbols/quantities.py
symplyphysics/definitions/angular_velocity_is_angle_derivative.py
symplyphysics/laws/dynamics/torque_due_to_twisting_force.py
symplyphysics/laws/kinematic/angular_frequency_from_radians_per_time.py
symplyphysics/laws/kinematic/planar_projection_is_cosine.py
symplyphysics/laws/optics/refraction_angle_from_environments.py
symplyphysics/laws/relativistic/waves/frequency_shift_from_velocity_and_angle.py
symplyphysics/laws/waves/frequency_shift_from_velocity_and_angle.py
test/core/symbols/quantities_test.py

I suppose we use this hack enough that it deserves its own function.

Core: scale_factor function

---

symplyphysics/laws/optics/radiation_intensity_from_energy_area_time.py
test/optics/radiation_intensity_from_energy_area_time_test.py

Commit #1. radiation_intensity

---

symplyphysics/laws/relativistic/relativistic_momentum.py
test/relativistic/relativistic_momentum_test.py

Commit #1. relativistic_momentum

---

symplyphysics/laws/gravity/maximum_height_of_a_body_thrown_at_an_angle_to_horizon.py
test/gravity/maximum_height_of_a_body_thrown_at_an_angle_to_horizon_test.py

Add law and tests.
I had to recreate the branch. The old  pull request has closed.
https://github.com/blackyblack/symplyphysics/pull/334

Maximum height of a body thrown at an angle to horizon

---

symplyphysics/laws/hydro/surface_tension_force_of_liquid.py
test/hydro/surface_tension_force_of_liquid_test.py

Commit #1. surface_tension_force_of_liquid

---

symplyphysics/laws/hydro/mach_number.py
test/hydro/mach_number_test.py

mach number

---

symplyphysics/laws/thermodynamics/grashof_number.py
test/thermodynamics/grashof_number_test.py

grashof number

---

symplyphysics/laws/thermodynamics/gas_pressure_from_temperature.py
test/thermodynamics/gas_pressure_from_temperature_test.py

Commit #1. gas_pressure_from_temperature

---

symplyphysics/laws/thermodynamics/isobaric_reaction_potential.py
test/thermodynamics/isobaric_reaction_potential_test.py

Isobaric reaction potential

---

symplyphysics/laws/thermodynamics/isobaric_potential_of_temperature_dependent_heat_capacity.py
test/thermodynamics/isobaric_potential_of_temperature_dependent_heat_capacity_test.py

Commit #1. isobaric_potential_of_temperature_dependent_heat_capacity

---

symplyphysics/laws/condensed_matter/reaction_equilibrium_constant.py
test/condensed_matter/reaction_equilibrium_constant_test.py

Commit #1. reaction_equilibrium_constant

---

symplyphysics/laws/thermodynamics/relative_humidity.py
test/thermodynamics/relative_humidity_test.py

Commit #1. relative_humidity

---

symplyphysics/definitions/wave_equation_in_one_dimension.py
test/definitions/wave_equation_in_one_dimension_test.py

I'm not sure what `calculate` function we could have here though.

Wave equation

---

symplyphysics/laws/electricity/voltage_in_rotating_rod.py
test/electricity/voltage_in_rotating_rod_test.py

Commit #1. voltage_in_rotating_rod

---

symplyphysics/laws/electricity/circuits/power_by_resistor_in_alternating_current_circuit.py
test/electricity/circuits/power_by_resistor_in_alternating_current_circuit_test.py

Commit #1. power_by_resistor_in_alternating_current_circuit

---

symplyphysics/laws/electricity/instantaneous_energy_of_electric_field.py
test/electricity/instantaneous_energy_of_electric_field_test.py

instantaneous_energy_of_electric_field

---

symplyphysics/laws/astronomy/relationship_of_periods_of_planets_with_semi_axes_of_orbits.py
test/astronomy/relationship_of_periods_of_planets_with_semi_axes_of_orbits_test.py

kepler_third_law

---

symplyphysics/laws/astronomy/eccentricity_of_orbit.py
test/astronomy/eccentricity_of_orbit_test.py

 eccentricity_of_orbit

---

symplyphysics/laws/astronomy/speed_of_galaxy_from_distance_to_galaxy.py
test/astronomy/speed_of_galaxy_from_distance_to_galaxy_test.py

speed_of_galaxy_from_distance_to_galaxy

---

symplyphysics/laws/gravity/gravitational_radius_of_body_mass.py
test/gravity/gravitational_radius_of_body_mass_test.py

gravitational_radius_of_body_mass

---

symplyphysics/laws/astronomy/angular_magnification_telescope.py
test/astronomy/angular_magnification_telescope_test.py

angular_magnification

---

symplyphysics/laws/astronomy/resolution_of_telescope.py
test/astronomy/resolution_of_telescope_test.py

resolution_of_telescope

---

symplyphysics/laws/gravity/escape_velocity.py
symplyphysics/laws/gravity/second_escape_velocity.py
test/gravity/second_escape_velocity_test.py

- add proof for "escape_velocity"
- add law, proof and tests

Second cosmic velocity

---

symplyphysics/laws/astronomy/relative_aperture_of_telescope.py
test/astronomy/relative_aperture_of_telescope_test.py

relative_aperture_of_telescope

---

symplyphysics/laws/astronomy/penetrating_power_of_telescope.py
test/astronomy/penetrating_power_of_telescope_test.py

penetrating_power_of_telescope

---

symplyphysics/laws/astronomy/absolute_magnitude_of_apparent_magnitude_and_distance.py
test/astronomy/absolute_magnitude_of_apparent_magnitude_and_distance_test.py

absolute_magnitude

---

symplyphysics/laws/astronomy/speed_of_rocket_depends_on_mass_and_impulse.py
test/astronomy/speed_of_rocket_depends_on_mass_and_impulse_test.py

Commit #1. speed_of_rocket_depends_on_mass_and_impulse

---

symplyphysics/laws/astronomy/change_in_apparent_magnitude_from_distance.py
test/astronomy/change_in_apparent_magnitude_from_distance_test.py

Commit #1. change_in_apparent_magnitude_from_distance

---

symplyphysics/laws/astronomy/radius_of_geostationary_orbit.py
test/astronomy/radius_of_geostationary_orbit_test.py

radius_of_geostationary_orbit

---

symplyphysics/laws/astronomy/ratio_of_luminosities_from_ratio_of_masses_of_stars.py
test/astronomy/ratio_of_luminosities_from_ratio_of_masses_of_stars_test.py

ratio_of_luminosities_from_ratio_of_masses_of_stars

---

symplyphysics/laws/astronomy/luminosity_of_star_from_absolute_magnitude.py
test/astronomy/luminosity_of_star_from_absolute_magnitude_test.py

luminosity_of_star_from_absolute_magnitude

---

symplyphysics/laws/astronomy/radius_of_planets_orbit_from_its_number.py
test/astronomy/radius_of_planets_orbit_from_its_number_test.py

radius_of_planets_orbit_from_its_number

---

symplyphysics/laws/astronomy/maximum_angle_of_rotation_during_gravitational_maneuver.py
test/astronomy/maximum_angle_of_rotation_during_gravitational_maneuver_test.py

maximum_angle_of_rotation_during_gravitational_maneuver

---

symplyphysics/laws/astronomy/lifetime_of_star_on_main_sequence.py
test/astronomy/lifetime_of_star_on_main_sequence_test.py

lifetime_of_star_on_main_sequence

---

symplyphysics/laws/astronomy/third_cosmic_velocity_from_orbital_and_second_velocities.py
test/astronomy/third_cosmic_velocity_from_orbital_and_second_velocities_test.py

third_cosmic_velocity_from_orbital_and_second_velocities

---

symplyphysics/laws/astronomy/relationship_of_periods_of_planets_with_mass_and_semi_axes_of_orbits.py
test/astronomy/relationship_of_periods_of_planets_with_mass_and_semi_axes_of_orbits_test.py

relationship_of_periods_of_planets_with_mass_and_semi_axes_of_orbits

---

symplyphysics/laws/electricity/circuits/resistance_of_resistor_in_wilkinson_divider.py
test/electricity/circuits/resistance_of_resistor_in_wilkinson_divider_test.py

resistance_of_resistor_in_wilkinson_divider

---

symplyphysics/laws/astronomy/approximate_time_of_stars_location_on_the_main_sequence.py
test/astronomy/approximate_time_of_stars_location_on_the_main_sequence_test.py

approximate_time_of_stars_location_on_the_main_sequence

---

symplyphysics/laws/astronomy/latitude_from_zenith_distances_and_declinations.py
test/astronomy/latitude_from_zenith_distances_and_declinations_test.py

latitude_from_zenith_distances_and_declinations

---

symplyphysics/laws/electricity/circuits/specific_inductance_of_coaxial_waveguide.py
test/electricity/circuits/specific_inductance_of_coaxial_waveguide_test.py

specific_inductance_of_coaxial_waveguide

---

symplyphysics/laws/electricity/circuits/specific_resistance_of_coaxial_waveguide.py
test/electricity/circuits/specific_resistance_of_coaxial_waveguide_test.py

specific_resistance_of_coaxial_waveguide

---

symplyphysics/laws/electricity/circuits/specific_conductivity_of_coaxial_waveguide.py
test/electricity/circuits/specific_conductivity_of_coaxial_waveguide_test.py

specific_conductivity_of_coaxial_waveguide

---

symplyphysics/laws/electricity/circuits/wave_resistance_of_coaxial_waveguide.py
test/electricity/circuits/wave_resistance_of_coaxial_waveguide_test.py

wave_resistance_of_coaxial_waveguide

---

symplyphysics/laws/electricity/circuits/surface_resistance_of_metal.py
test/electricity/circuits/surface_resistance_of_metal_test.py

surface_resistance_of_metal

---

symplyphysics/laws/electricity/circuits/attenuation_coefficient_in_metal.py
test/electricity/circuits/attenuation_coefficient_in_metal_test.py

attenuation_coefficient_in_metal

---

symplyphysics/laws/electricity/circuits/critical_wavelength_in_rectangular_waveguide.py
test/electricity/circuits/critical_wavelength_in_rectangular_waveguide_test.py

critical_wavelength_in_rectangular_waveguide

---

symplyphysics/laws/electricity/circuits/phase_velocity_of_wave_in_rectangular_waveguide.py
test/electricity/circuits/phase_velocity_of_wave_in_rectangular_waveguide_test.py

phase_velocity_of_wave_in_rectangular_waveguide

---

symplyphysics/laws/electricity/circuits/wavelength_in_rectangular_waveguide.py
test/electricity/circuits/wavelength_in_rectangular_waveguide_test.py

wavelength_in_rectangular_waveguide

---

symplyphysics/laws/electricity/circuits/group_velocity_of_wave_in_rectangular_waveguide.py
test/electricity/circuits/group_velocity_of_wave_in_rectangular_waveguide_test.py

group_velocity_of_wave_in_rectangular_waveguide

---

symplyphysics/laws/electricity/circuits/attenuation_coefficient_in_metal_in_rectangular_waveguide_for_transverse_magnetic_waves.py
test/electricity/circuits/attenuation_coefficient_in_metal_in_rectangular_waveguide_for_transverse_magnetic_waves_test.py

attenuation_coefficient_in_metal_in_rectangular_waveguide_for_transverse_magnetic_waves

---

symplyphysics/laws/electricity/circuits/attenuation_coefficient_in_dielectric_in_rectangular_waveguide.py
test/electricity/circuits/attenuation_coefficient_in_dielectric_in_rectangular_waveguide_test.py

attenuation_coefficient_in_dielectric_in_rectangular_waveguide

---

symplyphysics/laws/electricity/circuits/attenuation_coefficient_in_metal_in_rectangular_waveguide_for_transverse_electric_waves.py
test/electricity/circuits/attenuation_coefficient_in_metal_in_rectangular_waveguide_for_transverse_electric_waves_test.py

attenuation_coefficient_in_metal_in_rectangular_waveguide_for_transverse_electric_waves

---

symplyphysics/laws/electricity/circuits/power_carried_by_coaxial_waveguide.py
test/electricity/circuits/power_carried_by_coaxial_waveguide_test.py

power_carried_by_coaxial_waveguide

---

symplyphysics/laws/electricity/circuits/resonant_frequency_of_rectangular_resonator.py
test/electricity/circuits/resonant_frequency_of_rectangular_resonator_test.py

resonant_frequency_of_rectangular_resonator

---

symplyphysics/laws/electricity/circuits/quality_factor_of_filled_rectangular_resonator.py
test/electricity/circuits/quality_factor_of_filled_rectangular_resonator_test.py

quality_factor_of_filled_rectangular_resonator

---

symplyphysics/laws/electricity/waveguides/power_carried_by_main_wave_of_rectangular_waveguide.py
test/electricity/waveguides/power_carried_by_main_wave_of_rectangular_waveguide_test.py

power_carried_by_main_wave_of_rectangular_waveguide

---

symplyphysics/laws/electricity/circuits/total_conductivities_matrix.py
test/electricity/circuits/total_conductivities_matrix_test.py

total_conductivities_matrix

---

symplyphysics/laws/electricity/circuits/transmission_matrix.py
test/electricity/circuits/transmission_matrix_test.py

transmission_matrix

---

symplyphysics/laws/electricity/circuits/scattering_matrix_to_transmission_matrix.py
test/electricity/circuits/scattering_matrix_to_transmission_matrix_test.py

scattering_matrix_to_transmission_matrix

---

symplyphysics/laws/electricity/circuits/scattering_matrix.py
test/electricity/circuits/scattering_matrix_test.py

scattering_matrix

---

symplyphysics/laws/electricity/circuits/transmission_matrix_lossless_transmission_line.py
test/electricity/circuits/transmission_matrix_lossless_transmission_line_test.py

transmission_matrix_lossless_transmission_line

---

symplyphysics/laws/electricity/circuits/input_impedance_lossless_transmission_line.py
test/electricity/circuits/input_impedance_lossless_transmission_line_test.py

input_resistance_lossless_transmission_line

---

symplyphysics/laws/electricity/transmission_lines/transmission_matrix_for_a_series_load_in_line.py
test/electricity/transmission_lines/transmission_matrix_for_a_series_load_in_line_test.py

transmission_matrix_for_a_series_load_in_line

---

symplyphysics/laws/electricity/transmission_lines/transmission_matrix_for_a_parallel_load_in_line.py
test/electricity/transmission_lines/transmission_matrix_for_a_parallel_load_in_line_test.py

transmission_matrix_for_a_parallel_load_in_line

---

symplyphysics/laws/electricity/transmission_lines/transmission_matrix_of_t_type_circuit.py
test/electricity/transmission_lines/transmission_matrix_of_t_type_circuit_test.py

transmission_matrix_of_t_type_circuit

---

symplyphysics/laws/electricity/transmission_lines/impedances_t_type_circuit_of_transmission_line.py
test/electricity/transmission_lines/impedances_t_type_circuit_of_transmission_line_test.py

impedances_t_type_circuit_of_transmission_line

---

symplyphysics/laws/electricity/circuits/conductivity_for_rectangular_loop_coupler.py
test/electricity/circuits/conductivity_for_rectangular_loop_coupler_test.py

conductivity_for_rectangular_loop_coupler

---

symplyphysics/laws/electricity/circuits/length_of_section_of_multistage_transformer.py
test/electricity/circuits/length_of_section_of_multistage_transformer_test.py

length_of_section_of_multistage_transformer

---

symplyphysics/laws/electricity/circuits/transient_attenuation_of_separate_loop_coupler_with_cascade_connection.py
test/electricity/circuits/transient_attenuation_of_separate_loop_coupler_with_cascade_connection_test.py

transient_attenuation_of_separate_loop_coupler_with_cascade_connection

---

symplyphysics/laws/electricity/couplers/wave_resistance_odd_mode_of_lange_coupler.py
test/electricity/couplers/wave_resistance_odd_mode_of_lange_coupler_test.py

wave_resistance_odd_mode_of_lange_coupler

---

symplyphysics/laws/electricity/couplers/wave_resistance_even_mode_of_lange_coupler.py
test/electricity/couplers/wave_resistance_even_mode_of_lange_coupler_test.py

wave_resistance_even_mode_of_lange_coupler

---

symplyphysics/laws/electricity/resonators/coupling_parameter_of_resonator_from_quality_factors.py
test/electricity/resonators/coupling_parameter_of_resonator_from_quality_factors_test.py

coupling_parameter_of_resonator_from_quality_factors

---

symplyphysics/laws/electricity/resonators/loaded_resonator_quality_factor_from_quality_factors.py
test/electricity/resonators/loaded_resonator_quality_factor_from_quality_factors_test.py

loaded_resonator_quality_factor_from_quality_factors

---

symplyphysics/laws/electricity/resonators/loaded_resonator_quality_factor_from_circuit_parameters.py
test/electricity/resonators/loaded_resonator_quality_factor_from_circuit_parameters_test.py

loaded_resonator_quality_factor_from_circuit_parameters

---

symplyphysics/laws/electricity/resonators/own_quality_factor_of_resonator.py
test/electricity/resonators/own_quality_factor_of_resonator_test.py

own_quality_of_resonator

---

symplyphysics/laws/electricity/resonators/resonant_frequency_of_ring_resonator.py
test/electricity/resonators/resonant_frequency_of_ring_resonator_test.py

resonant_frequency_of_ring_resonator

---

symplyphysics/laws/electricity/circuits/butterworth_filter_order_from_distortion_and_frequencies.py
test/electricity/circuits/butterworth_filter_order_from_distortion_and_frequencies_test.py

butterworth_filter_order_from_distortion_and_frequencies

---

symplyphysics/laws/electricity/circuits/filter_order_from_distortion_and_frequencies.py
test/electricity/circuits/filter_order_from_distortion_and_frequencies_test.py

finding_filter_order_from_equation

---

symplyphysics/laws/electricity/transmission_lines/reflection_coefficient_from_load_and_transmission_line_impedances.py
test/electricity/transmission_lines/reflection_coefficient_from_load_and_transmission_line_impedances_test.py

reflection_coefficient_from_load_and_transmission_line

---

symplyphysics/laws/electricity/circuits/low_pass_chebyshev_filter_order_from_distortion_and_frequencies.py
test/electricity/circuits/low_pass_chebyshev_filter_order_from_distortion_and_frequencies_test.py

chebyshev_filter_oder_from_distortion_and_frequencies

---

symplyphysics/laws/electricity/transmission_lines/wave_resistance_of_microstrip_line_for_effective_width_less_thickness.py
test/electricity/transmission_lines/wave_resistance_of_microstrip_line_for_effective_width_less_thickness_test.py

Commit #1. wave_resistance_of_microstrip_line_for_effective_width_less_thickness

---

symplyphysics/laws/electricity/circuits/band_pass_chebyshev_filter_oder_from_distortion_and_frequencies.py
test/electricity/circuits/band_pass_chebyshev_filter_oder_from_distortion_and_frequencies_test.py

band_pass_chebyshev_filter_oder_from_distortion_and_frequencies

---

symplyphysics/laws/electricity/transmission_lines/ratio_of_average_power_to_incident_power_from_standing_wave_coefficient.py
test/electricity/transmission_lines/ratio_of_average_power_to_incident_power_from_standing_wave_coefficient_test.py

ratio_of_average_power_to_incident_power_from_standing_wave_coefficient

---

symplyphysics/laws/electricity/transmission_lines/microstrip_lines/effective_width_for_microstrip_line_for_width_less_thickness.py
test/electricity/transmission_lines/microstrip_lines/effective_width_for_microstrip_line_for_width_less_thickness_test.py

effective_width_for_microstrip_line_for_width_less_thickness

---

symplyphysics/laws/electricity/transmission_lines/microstrip_lines/effective_width_for_microstrip_line_for_width_greater_thickness.py
test/electricity/transmission_lines/microstrip_lines/effective_width_for_microstrip_line_for_width_greater_thickness_test.py

effective_width_for_microstrip_line_for_width_greater_thickness

---

symplyphysics/laws/electricity/transmission_lines/microstrip_lines/effective_permittivity_for_microstrip_line_for_width_less_thickness.py
test/electricity/transmission_lines/microstrip_lines/effective_permittivity_for_microstrip_line_for_width_less_thickness_test.py

effective_permittivity_for_microstrip_line_for_width_less_thickness

---

symplyphysics/laws/electricity/transmission_lines/wave_resistance_of_microstrip_line_for_effective_width_greater_thickness.py
test/electricity/transmission_lines/wave_resistance_of_microstrip_line_for_effective_width_greater_thickness_test.py

wave_resistance_of_microstrip_line_for_effective_width_greater_thickness

---

symplyphysics/laws/electricity/transmission_lines/ratio_of_average_power_to_incident_power_from_reflection_coefficient.py
test/electricity/transmission_lines/ratio_of_average_power_to_incident_power_from_reflection_coefficient_test.py

ratio_of_average_power_to_incident_power_from_reflection_coefficient

---

symplyphysics/laws/electricity/transmission_lines/microstrip_lines/effective_permittivity_for_microstrip_line_for_width_greater_thickness.py
test/electricity/transmission_lines/microstrip_lines/effective_permittivity_for_microstrip_line_for_width_greater_thickness_test.py

effective_permittivity_for_microstrip_line_for_width_greater_thickness

---

symplyphysics/laws/electricity/transmission_lines/microstrip_lines/effective_permittivity_for_microstrip_line_from_frequency.py
test/electricity/transmission_lines/microstrip_lines/effective_permittivity_for_microstrip_line_from_frequency_test.py

effective_permittivity_for_microstrip_line_from_frequency

---

symplyphysics/laws/electricity/transmission_lines/microstrip_lines/wave_resistance_of_microstrip_line_from_frequency.py
test/electricity/transmission_lines/microstrip_lines/wave_resistance_of_microstrip_line_from_frequency_test.py

wave_resistance_of_microstrip_line_from_frequency

---

symplyphysics/laws/electricity/transmission_lines/coplanar_lines/effective_permettivity_for_coplanar_transmission_line_for_distance_greater_thickness.py
test/electricity/transmission_lines/coplanar_lines/effective_permettivity_for_coplanar_transmission_line_for_distance_greater_thickness_test.py

effective_permettivity_for_coplanar_transmission_line_for_gap_greater_thickness

---

symplyphysics/laws/electricity/transmission_lines/coplanar_lines/effective_permettivity_for_coplanar_transmission_line_for_distance_less_thickness.py
test/electricity/transmission_lines/coplanar_lines/effective_permettivity_for_coplanar_transmission_line_for_distance_less_thickness_test.py

effective_permettivity_for_coplanar_transmission_line_for_distance_less_thickness

---

symplyphysics/laws/electricity/transmission_lines/coplanar_lines/wave_resistance_of_coplanar_line_first.py
symplyphysics/laws/electricity/transmission_lines/coplanar_lines/wave_resistance_of_coplanar_line_second.py
test/electricity/transmission_lines/coplanar_lines/wave_resistance_of_coplanar_line_first_test.py
test/electricity/transmission_lines/coplanar_lines/wave_resistance_of_coplanar_line_second_test.py

wave_resistance_of_coplanar_line

---

symplyphysics/laws/electricity/transmission_lines/microstrip_lines/microstrip_line_resistance.py
test/electricity/transmission_lines/microstrip_lines/microstrip_line_resistance_test.py

microstrip_line_resistance

---

symplyphysics/laws/electricity/transmission_lines/microstrip_lines/inductance_of_the_microstrip_line_strip.py
test/electricity/transmission_lines/microstrip_lines/inductance_of_the_microstrip_line_strip_test.py

inductance_of_the_microstrip_line_strip

---

symplyphysics/laws/electricity/transmission_lines/microstrip_lines/short_circuit_inductance_of_microstrip_line.py
test/electricity/transmission_lines/microstrip_lines/short_circuit_inductance_of_microstrip_line.py

short_circuit_inductance_of_microstrip_line

---

symplyphysics/laws/chemistry/cross_section_of_interaction_in_model_of_quasirigid_spheres.py
test/chemistry/cross_section_of_interaction_in_model_of_quasirigid_spheres_test.py

cross_section_of_interaction_in_model_of_quasirigid_spheres

---

symplyphysics/laws/chemistry/cross_section_of_interaction_in_coulomb_interaction_model.py
test/chemistry/cross_section_of_interaction_in_coulomb_interaction_model_test.py

cross_section_of_interaction_in_coulomb_interaction_model

---

symplyphysics/laws/chemistry/boundary_of_thermalization_zone_of_atomized_atoms_in_magnetron.py
test/chemistry/boundary_of_thermalization_zone_of_atomized_atoms_in_magnetron_test.py

boundary_of_thermalization_zone_of_atomized_atoms_in_magnetron

---

symplyphysics/laws/chemistry/number_of_collisions_of_atomized_atom_with_gas_atoms_in_magnetron.py
test/chemistry/number_of_collisions_of_atomized_atom_with_gas_atoms_in_magnetron_test.py

number_of_collisions_of_atomized_atom_with_gas_atoms_in_magnetron

---

symplyphysics/laws/chemistry/free_path_of_atomic_particles_in_gaseous_medium.py
test/chemistry/free_path_of_atomic_particles_in_gaseous_medium_test.py

free_path_of_atomic_particles_in_gaseous_medium

---

symplyphysics/laws/chemistry/cross_section_of_interaction_in_elastic_interaction_model.py
test/chemistry/cross_section_of_interaction_in_elastic_interaction_model_test.py

cross_section_of_interaction_in_elastic_interaction_model

---

symplyphysics/laws/chemistry/etching_rate_of_target_in_magnetron.py
test/chemistry/etching_rate_of_target_in_magnetron_test.py

etching_rate_of_target_in_magnetron

---

symplyphysics/laws/electricity/circuits/full_gain_of_transistor_amplifier.py
test/electricity/circuits/full_gain_of_transistor_amplifier_test.py

full_gain_of_transistor_amplifier

---

symplyphysics/laws/electricity/circuits/input_impedance_of_thin_film_resistor.py
test/electricity/circuits/input_impedance_of_thin_film_resistor_test.py

input_impedance_of_thin_film_resistor

---

symplyphysics/laws/electricity/circuits/steepness_of_volt_ampere_characteristic_of_vacuum_diode.py
test/electricity/circuits/steepness_of_volt_ampere_characteristic_of_vacuum_diode_test.py

steepness_of_volt_ampere_characteristic_of_vacuum_diode

---

symplyphysics/laws/electricity/circuits/varactor_junction_p_n_capacity.py
test/electricity/circuits/varactor_junction_p_n_capacity_test.py

varactor_junction_p_n_capacity

---

symplyphysics/laws/chemistry/mass_of_film_deposited_during_electrolysis.py
test/chemistry/mass_of_film_deposited_during_electrolysis_test.py

mass_of_film_deposited_during_electrolysis

---

symplyphysics/laws/electricity/circuits/limit_operating_frequency_of_vacuum_diode.py
test/electricity/circuits/limit_operating_frequency_of_vacuum_diode_test.py

limit_operating_frequency_of_vacuum_diode

---

symplyphysics/laws/electricity/circuits/internal_resistance_of_vacuum_diode.py
test/electricity/circuits/internal_resistance_of_vacuum_diode_test.py

internal_resistance_of_vacuum_diode

---

symplyphysics/laws/electricity/circuits/diode_constant_of_cylindrical_diode.py
test/electricity/circuits/diode_constant_of_cylindrical_diode_test.py

diode_constant_of_cylindrical_diode

---

symplyphysics/laws/electricity/circuits/diode_constant_for_plane_parallel_diode.py
test/electricity/circuits/diode_constant_for_plane_parallel_diode_test.py

diode_constant_for_plane_parallel_diode

---

symplyphysics/laws/electricity/circuits/current_from_voltage_and_triode_constant_in_vacuum_triode.py
test/electricity/circuits/current_from_voltage_and_triode_constant_in_vacuum_triode_test.py

current_from_voltage_and_triode_constant_in_vacuum_triode

---

symplyphysics/laws/chemistry/distance_of_greatest_convergence_of_particles_in_magnetron.py
test/chemistry/distance_of_greatest_convergence_of_particles_in_magnetron_test.py

distance_of_greatest_convergence_of_particles_in_magnetron

---

symplyphysics/laws/chemistry/cross_section_of_ionization_of_atom_by_electron_by_lotz_drevin.py
test/chemistry/cross_section_of_ionization_of_atom_by_electron_by_lotz_drevin_test.py

cross_section_of_ionization_of_atom_by_electron_by_lotz_drevin

---

symplyphysics/laws/electricity/corona_discharge_current_from_voltage.py
test/electricity/corona_discharge_current_from_voltage_test.py

corona_discharge_current_from_voltage

---

symplyphysics/laws/chemistry/cross_section_of_ionization_of_atom_by_electron_by_granovsky.py
test/chemistry/cross_section_of_ionization_of_atom_by_electron_by_granovsky_test.py

cross_section_of_ionization_of_atom_by_electron_by_granovsky

---

symplyphysics/laws/chemistry/electron_distribution_function_in_gas_plasma_by_maxwell.py
test/chemistry/electron_distribution_function_in_gas_plasma_by_maxwell_test.py

electron_distribution_function_in_gas_plasma_by_maxwell

---

symplyphysics/laws/chemistry/electron_distribution_function_in_gas_plasma_by_druyvestein.py
test/chemistry/electron_distribution_function_in_gas_plasma_by_druyvestein_test.py

electron_distribution_function_in_gas_plasma_by_druyvestein

---

symplyphysics/laws/chemistry/velocity_of_directional_motion_of_charged_particles_in_gas.py
test/chemistry/velocity_of_directional_motion_of_charged_particles_in_gas_test.py

velocity_of_directional_motion_of_charged_particles_in_gas

---

symplyphysics/laws/electricity/circuits/voltage_of_equivalent_diode_for_triode.py
test/electricity/circuits/voltage_of_equivalent_diode_for_triode_test.py

voltage_of_equivalent_diode_for_triode

---

symplyphysics/laws/chemistry/electronic_current_in_probe_circuit_in_gas_plasma.py
test/chemistry/electronic_current_in_probe_circuit_in_gas_plasma_test.py

electronic_current_in_probe_circuit_in_gas_plasma

---

symplyphysics/laws/electricity/circuits/voltage_of_equivalent_diode_for_tetrode.py
test/electricity/circuits/voltage_of_equivalent_diode_for_tetrode_test.py

voltage_of_equivalent_diode_for_tetrode

---

symplyphysics/laws/electricity/circuits/voltage_of_equivalent_diode_for_pentode.py
test/electricity/circuits/voltage_of_equivalent_diode_for_pentode_test.py

voltage_of_equivalent_diode_for_pentode

---

symplyphysics/laws/electricity/circuits/space_charge_density_in_diode_device.py
test/electricity/circuits/space_charge_density_in_diode_device_test.py

space_charge_density_in_diode_device

---

symplyphysics/laws/electricity/circuits/direct_permeability_coefficient_for_triode_with_flat_electrodes.py
test/electricity/circuits/direct_permeability_coefficient_for_triode_with_flat_electrodes_test.py

direct_permeability_coefficient_for_triode_with_flat_electrodes
